# Generated by Django 3.2.5 on 2021-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clockout',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
